### ISSUE TITLE
`forge-build-out` doesn't work as expectation.

### ISSUE THREAD

**Issue by whbjzzwjxq** [a16z/halmos#191]
**Describe the bug**
I assume that `forge-build-out` option is used to indicate the output folder of foundry, however, it works as seeking the build output in that folder.

**To Reproduce**
Go to an empty folder and execute `forge init`.
After the initialization, execute `halmos -vvvv --function test --forge-build-out .cache`
Actually, `out` folder will be used to compile code and Halmos can't find the output.

**Environment:**
 - OS: macOS
 - Python version: 3.11.4 (With mini-conda)
 - Halmos and other dependency versions: Halmos 0.1.4
 - Foundry version: forge 0.2.0 (6672134 2023-08-06T08:43:05.364384000Z)

**Additional context**
Could Halmos use `--cache-path` when calling `forge test`?

**Comment by whbjzzwjxq** [comment]
The practical problem is that every time I run `halmos` and `forge`, they will clean up the cache folder individually.

**Comment by TechWizard9999** [comment]
@whbjzzwjxq I am intrested in it 
Please assign me this!!

**Comment by whbjzzwjxq** [comment]
> @whbjzzwjxq I am intrested in it Please assign me this!!

Hello, I am not the developer/maintainer of Halmos, but you could get in touch with any of them.

**Comment by karmacoma-eth** [comment]
I don't understand this issue, foundry says `--cache-path` is the compiler cache, which halmos does not use.

halmos relies on the project root (where foundry.toml lives) and the build output directory (which forge normally puts under <root>/out)

hence, I can't make sense of your repro instructions:

> After the initialization, execute halmos -vvvv --function test --forge-build-out .cache
> Actually, out folder will be used to compile code and Halmos can't find the output.

yes, that's why you shouldn't use `--forge-build-out .cache` but `--forge-build-out out` (the default value)
