### ISSUE TITLE
Nested startPrank() doesn't work

### ISSUE THREAD

**Issue by igorganich** [a16z/halmos#420]
**Describe the bug**
In foundry testing, we can use nested startPrank():
```solidity
startHoax(deployer, 1 << 80);
...
vm.startPrank(alice);
vm.stopPrank(); // stop alice prank
vm.stopPrank(); // stop deployer prank
```
But in Halmos it leads to crash:
```javascript
WARNING:halmos:Warning: setUp() execution encountered an issue at CALL: <function error at 0x7fb7a4c2cae0> 
```
**To Reproduce**
1) checkout on https://github.com/igorganich/damn-vulnerable-defi-halmos/pull/6/commits/f44a6864c406b4acf1797975588c12643be4799c
2) halmos --solver-timeout-assertion 0 --function check_theRewarder
3) Wait, setUp() in this test in quite long
**Environment:**
 - ubuntu wsl
 - Python 3.12.3
 - halmos 0.2.2.dev1+gd4cac2e

**Comment by daejunpark** [comment]
if i remember correctly, foundry previously didn't allow nested pranks, but it seems the behavior has changed.

i'm curious whether allowing nested pranks are intentional. it seems potentially confusing and prone to making mistakes. could you please provide a pointer to other use cases of nested pranks or the rationale behind them?

**Comment by karmacoma-eth** [comment]
in a test function, this fails with the expected error message:

```solidity
    function test_nestedPrank() external {
        vm.startPrank(address(0));
        vm.startPrank(address(0));
    }
```

(sort of)

```
WARNING  Encountered You have an active prank already.                                                                                                                                                                                                                                                        
         (see https://github.com/a16z/halmos/wiki/warnings#internal-error)
```

But in `setUp()`, the message is lost:

```
WARNING  Warning: setUp() execution encountered an issue at CALL: <function error at 0x10201fec0>                                                                                                                                                                                                             
         (see https://github.com/a16z/halmos/wiki/warnings#internal-error)                                                                                                                                                                                                                                              
ERROR    Error: setUp() failed: HalmosException: No successful path found in setUp()         
```

**Comment by karmacoma-eth** [comment]
I think we'd be happy if an external contributor added support for nested pranks (would need to change our Prank object to be a stack instead of a single value), but for now we'll focus on prioritizing core features. 

I'll close this for now after fixing the error message in https://github.com/a16z/halmos/pull/428
